version: '3'
services:
  composer:
    container_name: composer
    image: composer:2.0
    environment:
      - COMPOSER_CACHE_DIR=/app/.cache/composer
    volumes:
      - .:/app
  phpunit:
    container_name: phpunit
    image: php:8.0-cli
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit
